import { Activity, ArrowUpRight, CalendarDays, HeartHandshake, RefreshCw, TrendingUp, UsersRound } from 'lucide-react';
import { Link } from 'wouter';
import { getGetAnalyticsActivityQueryKey, getGetAnalyticsOverviewQueryKey, getListEventsQueryKey, useGetAnalyticsActivity, useGetAnalyticsOverview, useListEvents } from '@workspace/api-client-react';
import { AppShell, Button, EventCard, ErrorState, PageHeading, Skeleton, StatCard, formatDate } from '@/components/gatherly';

export default function Dashboard() {
  const overview = useGetAnalyticsOverview({ query: { queryKey: getGetAnalyticsOverviewQueryKey() } });
  const activity = useGetAnalyticsActivity({ query: { queryKey: getGetAnalyticsActivityQueryKey() } });
  const events = useListEvents({ timeframe: 'upcoming' }, { query: { queryKey: getListEventsQueryKey({ timeframe: 'upcoming' }) } });
  const refresh = () => { void overview.refetch(); void activity.refetch(); void events.refetch(); };
  if (overview.isLoading) return <AppShell><PageHeading eyebrow="ICGA organizer desk" title="Assalamu alaikum." /><div className="grid gap-4 md:grid-cols-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-36" />)}</div><Skeleton className="mt-8 h-72" /></AppShell>;
  if (overview.isError || !overview.data) return <AppShell><ErrorState onRetry={refresh} /></AppShell>;
  const metrics = overview.data;
  return <AppShell><div className="page-in"><PageHeading eyebrow="ICGA organizer desk" title="Assalamu alaikum." description="Here’s the shape of the ICGA community, at a glance." action={<Button variant="secondary" onClick={refresh} data-testid="button-refresh-dashboard"><RefreshCw size={15} className={overview.isFetching ? 'animate-spin' : ''} /> Refresh</Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Upcoming events" value={String(metrics.upcomingEvents)} detail={`${metrics.totalEvents} total at ICGA`} icon={CalendarDays} accent /><StatCard label="Registrations" value={metrics.totalRegistrations.toLocaleString()} detail={`${metrics.registrationChange >= 0 ? '+' : ''}${metrics.registrationChange}% from last month`} icon={UsersRound} /><StatCard label="Community giving" value={`$${metrics.totalRaised.toLocaleString()}`} detail={`${Math.round(metrics.goalProgress)}% of active goals`} icon={HeartHandshake} /><StatCard label="Average attendance" value={`${Math.round(metrics.averageAttendance)}%`} detail="of reserved seats filled" icon={TrendingUp} /></div>
     <div className="mt-8 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-card-border bg-card p-5 shadow-xs sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Next up</p><h2 className="mt-1 font-display text-2xl font-bold tracking-[-.04em]">Upcoming ICGA events</h2></div><Link href="/events/manage" data-testid="link-manage-events-dashboard" className="text-xs font-bold text-primary hover:underline">Manage all</Link></div>{events.isLoading ? <div className="space-y-3"><Skeleton className="h-28" /><Skeleton className="h-28" /></div> : events.data?.length ? <div className="space-y-3">{events.data.slice(0, 3).map((event) => <EventCard compact event={event} key={event.id} />)}</div> : <p className="rounded-xl bg-muted p-6 text-sm text-muted-foreground">No upcoming events yet. Your next ICGA program is waiting to be planned.</p>}</section><section className="rounded-2xl border border-card-border bg-card p-5 shadow-xs sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Live feed</p><h2 className="mt-1 font-display text-2xl font-bold tracking-[-.04em]">Recent activity</h2></div><Activity size={18} className="text-primary" /></div><div className="space-y-5">{activity.isLoading ? [1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-10" />) : activity.data?.length ? activity.data.slice(0, 5).map((item) => <div key={item.id} data-testid={`activity-${item.id}`} className="flex gap-3"><span className="mt-1.5 size-2 shrink-0 rounded-full bg-accent" /><div><p className="text-sm leading-5">{item.message}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[.1em] text-muted-foreground">{formatDate(item.createdAt, { month: 'short', day: 'numeric' })}</p></div></div>) : <p className="text-sm text-muted-foreground">Your next registration or donation will appear here.</p>}</div></section></div>
     <section className="mt-6 flex flex-col justify-between gap-4 rounded-2xl bg-secondary/75 p-5 sm:flex-row sm:items-center sm:p-6"><div><p className="font-display text-xl font-bold">Make the next invitation easy</p><p className="mt-1 text-sm text-muted-foreground">A clear ICGA event page is the best welcome.</p></div><Link href="/events/manage" data-testid="link-create-event-dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-primary">Create an event <ArrowUpRight size={16} /></Link></section>
  </div></AppShell>;
}