import { useState } from 'react';
import { ArrowLeft, CalendarDays, Check, Clock3, HeartHandshake, MapPin, UsersRound } from 'lucide-react';
import { Link, useLocation, useParams } from 'wouter';
import { getGetEventQueryKey, useCreateRegistration, useGetEvent } from '@workspace/api-client-react';
import { Button, ErrorState, Field, Skeleton, formatDate, inputClass } from '@/components/gatherly';
import { PublicShell } from '@/components/public-shell';

export default function EventDetail() {
  const params = useParams<{ eventId: string }>();
  const eventId = Number(params.eventId);
  const [, setLocation] = useLocation();
  const eventQuery = useGetEvent(eventId, { query: { enabled: Number.isFinite(eventId), queryKey: getGetEventQueryKey(eventId) } });
  const registration = useCreateRegistration();
  const [form, setForm] = useState({ name: '', email: '' });
  const [error, setError] = useState('');
  const event = eventQuery.data;
  if (eventQuery.isLoading) return <PublicShell><div className="page-in mx-auto max-w-5xl"><Skeleton className="h-[420px]" /><Skeleton className="mt-6 h-52" /></div></PublicShell>;
  if (eventQuery.isError || !event) return <PublicShell><ErrorState onRetry={() => eventQuery.refetch()} /></PublicShell>;
  const full = event.registeredCount >= event.capacity;
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(''); registration.mutate({ data: { eventId, name: form.name, email: form.email } }, { onSuccess: (result) => setLocation(`/register/${result.id}`), onError: () => setError('We could not save that registration. Please try again.') }); };
  return <PublicShell><div className="page-in mx-auto max-w-5xl"><Link href="/" data-testid="link-back-home" className="mb-7 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-primary"><ArrowLeft size={15} /> Back to the ICGA calendar</Link>
    <div className="grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><div><div className="relative flex min-h-[310px] items-end overflow-hidden rounded-[26px] p-7 sm:min-h-[420px] sm:p-10" style={{ background: `linear-gradient(135deg, hsl(${(event.id * 43) % 360} 42% 34%), hsl(${((event.id * 43) + 55) % 360} 50% 70%))` }}>{event.imageUrl && <img src={event.imageUrl} alt="" className="absolute inset-0 size-full object-cover mix-blend-multiply opacity-60" />}<div className="absolute inset-0 bg-gradient-to-t from-primary/80 via-primary/10 to-transparent" /><div className="relative text-primary-foreground"><span className="rounded-full bg-accent px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.13em] text-accent-foreground">{event.category}</span><h1 className="mt-5 max-w-2xl font-display text-4xl font-bold leading-[.95] tracking-[-.06em] sm:text-6xl">{event.title}</h1></div></div>
       <div className="mt-8"><div className="grid gap-4 border-b border-border pb-7 sm:grid-cols-3"><div className="flex gap-3"><CalendarDays className="mt-0.5 shrink-0 text-primary" size={18} /><div><p className="text-xs font-bold">When</p><p className="mt-1 text-sm text-muted-foreground">{formatDate(event.startsAt, { weekday: 'long', month: 'long', day: 'numeric' })}</p><p className="text-xs text-muted-foreground">{new Date(event.startsAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</p></div></div><div className="flex gap-3"><MapPin className="mt-0.5 shrink-0 text-primary" size={18} /><div><p className="text-xs font-bold">Where</p><p className="mt-1 text-sm text-muted-foreground">{event.location}</p></div></div><div className="flex gap-3"><UsersRound className="mt-0.5 shrink-0 text-primary" size={18} /><div><p className="text-xs font-bold">Seats left</p><p className="mt-1 text-sm text-muted-foreground">{Math.max(event.capacity - event.registeredCount, 0)} of {event.capacity}</p></div></div></div><div className="prose prose-sm mt-8 max-w-none text-muted-foreground"><p className="whitespace-pre-line leading-7">{event.description}</p></div></div>
    </div>
     <aside className="lg:sticky lg:top-8 lg:self-start"><div className="rounded-2xl border border-card-border bg-card p-5 shadow-md sm:p-6"><div className="flex items-center gap-2 text-sm font-bold"><Clock3 size={16} className="text-primary" /> {event.status === 'completed' ? 'This gathering has passed' : 'Register for this event'}</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{event.status === 'completed' ? 'This ICGA program has already happened.' : full ? 'This ICGA event is currently full. Join the waitlist and we will let you know if a seat opens.' : 'A few details and you’re on the list. No account needed.'}</p>{event.status === 'completed' ? null : <form onSubmit={submit} className="mt-6 space-y-4"><Field label="Your name"><input required minLength={2} data-testid="input-registration-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={inputClass} placeholder="How should we greet you?" /></Field><Field label="Email address"><input required type="email" data-testid="input-registration-email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className={inputClass} placeholder="you@example.com" /></Field>{error && <p className="rounded-lg bg-destructive/10 p-3 text-xs text-destructive" data-testid="status-registration-error">{error}</p>}<Button disabled={registration.isPending} type="submit" className="w-full">{registration.isPending ? 'Saving your seat…' : full ? 'Join the waitlist' : 'Register for ICGA event'} <Check size={16} /></Button></form>}</div><div className="mt-4 rounded-2xl border border-border bg-secondary/70 p-5"><div className="flex items-center gap-2 font-display font-bold"><HeartHandshake size={17} className="text-primary" /> Community impact</div><p className="mt-2 text-xs leading-5 text-muted-foreground">Supporting <strong className="text-foreground">{event.charityName}</strong></p><div className="mt-4 h-2 overflow-hidden rounded-full bg-card"><div className="h-full rounded-full bg-accent" style={{ width: `${Math.min(100, Math.round((event.charityRaised / Math.max(event.charityGoal, 1)) * 100))}%` }} /></div><p className="mt-2 text-[11px] text-muted-foreground">${event.charityRaised.toLocaleString()} raised of ${event.charityGoal.toLocaleString()} goal</p></div></aside>
  </div></div></PublicShell>;
}