import { useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Search, UsersRound } from 'lucide-react';
import { Link } from 'wouter';
import { getListEventsQueryKey, useListEvents } from '@workspace/api-client-react';
import { Button, EventCard, PageHeading, Skeleton, EmptyState, ErrorState } from '@/components/gatherly';
import { PublicShell } from '@/components/public-shell';

export default function Home() {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('all');
  const [timeframe, setTimeframe] = useState<'upcoming' | 'past'>('upcoming');
  const params = useMemo(() => ({ search: search || undefined, category: category === 'all' ? undefined : category, timeframe }), [search, category, timeframe]);
  const eventsQuery = useListEvents(params, { query: { queryKey: getListEventsQueryKey(params) } });
  const events = eventsQuery.data ?? [];
  const categories = Array.from(new Set(events.map((event) => event.category)));
  return <PublicShell><div className="page-in">
    <section className="relative mb-10 overflow-hidden rounded-[22px] bg-primary px-5 py-10 text-primary-foreground shadow-lg sm:mb-12 sm:rounded-[28px] sm:px-12 sm:py-16">
      <div className="absolute -right-24 -top-28 size-80 rounded-full border-[42px] border-accent/25" /><div className="absolute -bottom-40 right-24 size-72 rounded-full border-[32px] border-primary-foreground/10" />
       <div className="relative max-w-3xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-primary-foreground/20 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.15em] text-primary-foreground/70"><span className="size-1.5 rounded-full bg-accent" />ICGA Austin · Masjid community</p><h1 className="font-display text-[clamp(2.6rem,7vw,5.5rem)] font-bold leading-[.94] tracking-[-.07em]">Find your place<br /><span className="text-accent">at ICGA.</span></h1><p className="mt-6 max-w-xl text-sm leading-7 text-primary-foreground/70 sm:text-base">ICGA is where Austin Muslims gather for prayer, learning, service, and time together.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#upcoming" data-testid="link-browse-events" className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-3 text-sm font-bold text-accent-foreground hover:-translate-y-0.5 hover:shadow-md">Browse ICGA events <ArrowRight size={16} /></a><Link href="/events/manage" data-testid="link-organize-event" className="inline-flex items-center gap-2 rounded-xl border border-primary-foreground/20 px-4 py-3 text-sm font-bold text-primary-foreground hover:bg-primary-foreground/10">Add an event</Link></div></div>
       <div className="relative mt-12 grid max-w-2xl grid-cols-2 gap-4 border-t border-primary-foreground/15 pt-6 sm:grid-cols-3 sm:gap-6"><div className="min-w-0"><p className="font-display text-xl font-bold leading-tight sm:text-2xl">One ummah</p><p className="mt-1 text-xs text-primary-foreground/55">in every gathering</p></div><div className="min-w-0"><p className="font-display text-xl font-bold leading-tight sm:text-2xl">Austin rooted</p><p className="mt-1 text-xs text-primary-foreground/55">serving our neighbors</p></div><div className="hidden min-w-0 sm:block"><p className="font-display text-xl font-bold leading-tight sm:text-2xl">Open door</p><p className="mt-1 text-xs text-primary-foreground/55">everyone is welcome</p></div></div>
    </section>
    <section id="upcoming" className="scroll-mt-10">
       <PageHeading eyebrow="The ICGA calendar" title={timeframe === 'past' ? 'What already happened' : 'What’s happening next'} description={timeframe === 'past' ? 'Recent ICGA programs, kept so the community can look back.' : 'Prayer, learning, service, and time together for the Austin Muslim community.'} action={<Link href="/events/manage" data-testid="link-create-event-home" className="hidden items-center gap-2 text-sm font-bold text-primary hover:gap-3 sm:flex">Add an event <ArrowRight size={15} /></Link>} />
       <div className="mb-7 flex flex-col gap-3 md:flex-row md:items-center"><div className="flex w-full rounded-xl border border-border bg-card p-1 sm:w-auto">{(['upcoming', 'past'] as const).map((item) => <button type="button" key={item} data-testid={`button-timeframe-${item}`} onClick={() => { setTimeframe(item); setCategory('all'); }} className={`flex-1 rounded-lg px-3 py-2 text-xs font-bold capitalize sm:flex-none ${timeframe === item ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}>{item === 'upcoming' ? 'Upcoming' : 'Past programs'}</button>)}</div><label className="relative w-full max-w-md flex-1"><Search className="absolute left-3.5 top-3.5 text-muted-foreground" size={17} /><input data-testid="input-search-events" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search ICGA events, programs, places..." className="w-full rounded-xl border border-input bg-card py-3 pl-10 pr-4 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-ring/20" /></label><div className="-mx-4 flex gap-2 overflow-x-auto px-4 pb-1 md:mx-0 md:px-0">{['all', ...categories].map((item) => <button type="button" key={item} data-testid={`button-filter-${item}`} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-xl px-3.5 py-2 text-xs font-bold capitalize ${category === item ? 'bg-primary text-primary-foreground' : 'border border-border bg-card text-muted-foreground hover:bg-muted'}`}>{item === 'all' ? 'All ICGA events' : item}</button>)}</div></div>
      {eventsQuery.isLoading && <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((item) => <Skeleton key={item} className="h-[350px]" />)}</div>}
      {eventsQuery.isError && <ErrorState onRetry={() => eventsQuery.refetch()} />}
       {!eventsQuery.isLoading && !eventsQuery.isError && events.length === 0 && <EmptyState title="No ICGA events found" detail="Try a different search or check back soon. The calendar is always growing." action={<Button onClick={() => { setSearch(''); setCategory('all'); }}>Clear filters</Button>} />}
      {!eventsQuery.isLoading && !eventsQuery.isError && events.length > 0 && <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{events.map((event, index) => <div key={event.id} className="stagger-in" style={{ animationDelay: `${index * 65}ms` }}><EventCard event={event} /></div>)}</div>}
    </section>
    <section className="mt-20 grid gap-5 overflow-hidden rounded-[26px] border border-border bg-secondary/60 p-6 sm:grid-cols-[1.2fr_.8fr] sm:p-10"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">The ICGA promise</p><h2 className="mt-4 max-w-lg font-display text-3xl font-bold leading-tight tracking-[-.05em] sm:text-4xl">A masjid calendar should do more than fill a room.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground">Every ICGA program is a chance to strengthen faith, friendship, and service across Austin.</p></div><div className="grid grid-cols-2 gap-3 self-end"><div className="rounded-2xl bg-card p-4"><UsersRound className="text-primary" size={19} /><p className="mt-10 font-display text-xl font-bold">Community</p><p className="mt-1 text-xs text-muted-foreground">becomes connection</p></div><div className="rounded-2xl bg-card p-4"><CalendarDays className="text-primary" size={19} /><p className="mt-10 font-display text-xl font-bold">Service</p><p className="mt-1 text-xs text-muted-foreground">becomes impact</p></div></div></section>
  </div></PublicShell>;
}