import { useEffect } from 'react';
import { CalendarDays, Check, HeartHandshake, MapPin, Sparkles } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { getGetEventQueryKey, getGetRegistrationQueryKey, useGetEvent, useGetRegistration } from '@workspace/api-client-react';
import { ErrorState, Skeleton, formatDate } from '@/components/gatherly';
import { PublicShell } from '@/components/public-shell';

export default function RegistrationConfirmation() {
  const params = useParams<{ registrationId: string }>();
  const registrationId = Number(params.registrationId);
  const registrationQuery = useGetRegistration(registrationId, { query: { enabled: Number.isFinite(registrationId), queryKey: getGetRegistrationQueryKey(registrationId) } });
  const registration = registrationQuery.data;
  const eventQuery = useGetEvent(registration?.eventId ?? 0, { query: { enabled: !!registration?.eventId, queryKey: getGetEventQueryKey(registration?.eventId ?? 0) } });
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'smooth' }); }, []);
  if (registrationQuery.isLoading) return <PublicShell><div className="mx-auto max-w-2xl"><Skeleton className="h-[520px]" /></div></PublicShell>;
  if (registrationQuery.isError || !registration) return <PublicShell><ErrorState onRetry={() => registrationQuery.refetch()} /></PublicShell>;
  const event = eventQuery.data;
  return <PublicShell><div className="page-in mx-auto max-w-2xl py-4 sm:py-10"><div className="overflow-hidden rounded-[28px] border border-card-border bg-card shadow-md"><div className="bg-primary px-6 py-10 text-center text-primary-foreground sm:px-12"><div className="mx-auto grid size-16 place-items-center rounded-full bg-accent text-accent-foreground"><Check size={30} strokeWidth={2.5} /></div><p className="mt-6 font-mono text-[10px] uppercase tracking-[.2em] text-primary-foreground/60">ICGA registration confirmed</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.06em]">See you there, {registration.name.split(' ')[0]}.</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-primary-foreground/65">Your place is saved. Keep this confirmation, and watch {registration.email} for updates from ICGA.</p>{'ticketCode' in registration && registration.ticketCode ? <p className="mt-5 inline-flex rounded-full bg-primary-foreground/10 px-4 py-2 font-mono text-sm tracking-[.14em]">{String(registration.ticketCode)}</p> : null}</div><div className="p-6 sm:p-10">{eventQuery.isLoading ? <Skeleton className="h-28" /> : event ? <><div className="flex items-start gap-4"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-secondary text-primary"><Sparkles size={20} /></div><div><p className="font-mono text-[10px] uppercase tracking-[.15em] text-muted-foreground">Your ICGA event</p><h2 className="mt-1 font-display text-2xl font-bold tracking-[-.04em]">{event.title}</h2></div></div><div className="mt-8 space-y-4 border-y border-border py-6"><div className="flex gap-3 text-sm"><CalendarDays size={17} className="text-primary" /><span>{formatDate(event.startsAt, { weekday: 'long', month: 'long', day: 'numeric' })} · {new Date(event.startsAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</span></div><div className="flex gap-3 text-sm"><MapPin size={17} className="text-primary" /><span>{event.location}</span></div></div><div className="mt-6 rounded-xl bg-secondary/70 p-4"><div className="flex items-center gap-2 text-sm font-bold"><HeartHandshake size={16} className="text-primary" /> Community impact</div><p className="mt-1 text-xs leading-5 text-muted-foreground">This event is supporting {event.charityName}. Thanks for being part of the ICGA community.</p></div></> : null}<Link href="/" data-testid="link-return-bulletin" className="mt-7 inline-flex w-full items-center justify-center rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground hover:-translate-y-0.5">Find another ICGA event</Link></div></div></div></PublicShell>;
}